FROM python:latest

WORKDIR /app

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

RUN pip install --no-cache-dir prometheus-client prometheus-fastapi-instrumentator

VOLUME /app/data

EXPOSE 8001

ENV PYTHONUNBUFFERED=1

CMD uvicorn shop_api.main:app --host 0.0.0.0 --port 8001